{% set name = "causalpy" %}
{% set version = "0.4.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 1c021234c6a5f0242089225e29f8324d5de5e8cf0d728617565181024a3b50a8

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.10
    - setuptools >=61.0
  run:
    - python >=3.10
    - arviz >=0.14.0
    - python-graphviz
    - ipython !=8.7.0
    - matplotlib-base >=3.5.3
    - numpy
    - pandas
    - patsy
    - pymc >=5.14.0
    - scikit-learn >=1
    - scipy
    - seaborn >=0.11.2
    - statsmodels
    - xarray >=v2022.11.0

test:
  imports:
    - causalpy
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/pymc-labs/CausalPy
  doc_url: https://causalpy.readthedocs.io/
  summary: Causal inference for quasi-experiments in Python
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - maresb
    - thewchan
