{% set name = "causalpy" %}
{% set version = "0.0.7" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/CausalPy-{{ version }}.tar.gz
  sha256: 8bea895f499987ae1aff910a9160bd4b90458a508a29220ab699ef8e67bcc70e

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.8
  run:
    - arviz >=0.14.0
    - python-graphviz
    - matplotlib-base >=3.5.3
    - numpy
    - pandas
    - patsy
    - pymc >=4.0.0
    - python >=3.8
    - scikit-learn >=1
    - scipy
    - seaborn >=0.11.2
    - xarray >=v2022.11.0

test:
  imports:
    - causalpy
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/pymc-labs/CausalPy
  doc_url: https://causalpy.readthedocs.io/
  summary: Causal inference for quasi-experiments in Python
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - thewchan
